config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :courses
  resources :plans
  resources :regions
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "students#index"
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :region
  belongs_to :course
  #has_many :plans, through: :courses
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
      # @students = Student.includes(:course).order(created_at: :asc)
      @q = Student.ransack(params[:q])
      @students = @q.result(:distinct => true).includes(:course, :region)
      @courses = Course.all
      @regions = Region.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:rut, :name, :lastname1, :lastname2, :address, :region_id, :course_id)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :rut, style: "display: block" %>
    <%= form.text_field :rut %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :lastname1, style: "display: block" %>
    <%= form.text_field :lastname1 %>
  </div>

  <div>
    <%= form.label :lastname2, style: "display: block" %>
    <%= form.text_field :lastname2 %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_area :address %>
  </div>

  <div>
    <%= form.label :region_id, style: "display: block" %>
    <%= form.text_field :region_id %>
  </div>

  <div>
    <%= form.label :course_id, style: "display: block" %>
    <%= form.text_field :course_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/students/_student.html.erb
<div id="<%= dom_id student %>">

  <td>
    <%= student.rut %>
  </td>

  <td>
    <%= student.name %>
  </td>

  <td>
    <%= student.lastname1 %>
  </td>

  <td>
    <%= student.lastname2 %>
  </td>

  <td>
      <%= student.course.code %>
  </td>

    <td>
        <%= student.course.plan.description %>
  </td>

</div>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Show this student", @student %> |
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/index.html.erb
<h1 class="text-center">Estudiantes</h1>
<div class="container">
  <%= search_form_for @q do |f| %>
    <div class="d-flex align-items-center bg-white rounded-top p-3">
    <div class="col-3 me-3">
        <%= f.label :region_name_cont, 'Region', :class => 'form-label d-block p-0 m-0 fw-bold' %>
        <%= f.select :region_name_cont, options_for_select(@regions.map { |r| [r.name]}), {:include_blank => "Elige una region"}, {:class => 'form-select'} %>
      </div>
      <div class="col-3">
        <%= f.label :course_code_cont, "Curso", :class => 'form-label d-block p-0 m-0 fw-bold' %>
        <%= f.select :course_code_cont, options_for_select(@courses.map { |c| [c.code]}), {:include_blank => "Elige un curso"}, {:class => 'form-select'} %>
      </div>
      <div class="ms-3 align-self-end">
        <%= f.submit "Filtrar", {:class => 'btn btn-primary p-4'} %>
      </div>
    </div>
  <% end %>
</div>


<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Rut</th>
      <th scope="col">Nombre</th>
      <th scope="col">Apellido Paterno</th>
      <th scope="col">Apellido Naterno</th>
      <th scope="col">Codigo Curso</th>
      <th scope="col">Descripcion Curso</th>
      <th></th>
    </tr>
  </thead>
  <tbody class="table-group-divider">
<div id="students">
  <% @students.each do |student| %>
  <tr>
      <%= render student %>
      <td> <%= link_to "Ver", student , class:'btn btn-primary'%> </td>
    </tr>
  <% end %>
  </tbody>
  </table>
</div>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/show.html.erb
<div class="d-flex flex-wrap justify-content-center">
  <div class="card text-dark my-3" style="max-width: 540px;">
    <div class="row m-0 p-0">
      <div class="col-4" style="width: 300px">
      </div>
      <div class="col-8 border-start border-secondary p-0 m-0">
        <div class="card-body bg-white p-0 m-0 rounded-end">
          <h5 class="card-title p-0 m-0 ps-3 my-3">
            <strong>Nombre:</strong>
            <%=@student.name  %>
          </h5>
          <p class="card-text p-0 ps-3">
            <strong>Rut:</strong>
            <%=@student.rut  %>
          </p>
          <p class="card-text p-0 ps-3">
            <strong>Apellido Paterno:</strong>
            <%=@student.lastname1  %>
          </p>
          <p class="card-text p-0 ps-3">
            <strong>Apellido Materno:</strong>
            <%=@student.lastname2  %>
          </p>
          <p class="card-text p-0 ps-3">
            <strong>Code:</strong>
            <%=@student.course.code  %>
          </p>
          <p class="card-text p-0 ps-3">
            <strong>Descripcion:</strong>
            <%=@student.course.plan.description  %>
          </p>
          <p class="card-text m-0 p-0 ps-3">
            <small class="text-muted">
              <strong>Fecha Inicio:</strong>
              <%=@student.course.startdate %>
            </small>
          </p>
          <p class="card-text p-0 ps-3">
            <small class="text-muted">
              <strong>Fecha Termino:</strong>
              <%=@student.course.enddate  %>
            </small>
          </p>
        </div>
        <p class="card-footer d-flex justify-content-start m-0 p-0">
        </p>
      </div> 
    </div> 
  </div> 
  <div class="col-12 text-center">
  <h3><%= link_to "Volver", students_path, class:"badge text-bg-secondary border border-white border-2 fw-bold ms-auto"%></h3>
</div>
</div> 