config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :courses
  resources :plans
  resources :regions
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "students#index"
end

app/models/region.rb
class Region < ApplicationRecord
    has_many :courses
    has_many :students
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  before_action :set_region, only: %i[ show edit update destroy ]

  # GET /regions or /regions.json
  def index
    @regions = Region.all
  end

  # GET /regions/1 or /regions/1.json
  def show
  end

  # GET /regions/new
  def new
    @region = Region.new
  end

  # GET /regions/1/edit
  def edit
  end

  # POST /regions or /regions.json
  def create
    @region = Region.new(region_params)

    respond_to do |format|
      if @region.save
        format.html { redirect_to region_url(@region), notice: "Region was successfully created." }
        format.json { render :show, status: :created, location: @region }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /regions/1 or /regions/1.json
  def update
    respond_to do |format|
      if @region.update(region_params)
        format.html { redirect_to region_url(@region), notice: "Region was successfully updated." }
        format.json { render :show, status: :ok, location: @region }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /regions/1 or /regions/1.json
  def destroy
    @region.destroy

    respond_to do |format|
      format.html { redirect_to regions_url, notice: "Region was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_region
      @region = Region.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def region_params
      params.require(:region).permit(:name)
    end
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/views/regions/_form.html.erb
<%= form_with(model: region) do |form| %>
  <% if region.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(region.errors.count, "error") %> prohibited this region from being saved:</h2>

      <ul>
        <% region.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/regions/_region.html.erb
<div id="<%= dom_id region %>">
  <p>
    <strong>Name:</strong>
    <%= region.name %>
  </p>

</div>

app/views/regions/edit.html.erb
<h1>Editing region</h1>

<%= render "form", region: @region %>

<br>

<div>
  <%= link_to "Show this region", @region %> |
  <%= link_to "Back to regions", regions_path %>
</div>

app/views/regions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Regions</h1>

<div id="regions">
  <% @regions.each do |region| %>
    <%= render region %>
    <p>
      <%= link_to "Show this region", region %>
    </p>
  <% end %>
</div>

<%= link_to "New region", new_region_path %>

app/views/regions/new.html.erb
<h1>New region</h1>

<%= render "form", region: @region %>

<br>

<div>
  <%= link_to "Back to regions", regions_path %>
</div>

app/views/regions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @region %>

<div>
  <%= link_to "Edit this region", edit_region_path(@region) %> |
  <%= link_to "Back to regions", regions_path %>

  <%= button_to "Destroy this region", @region, method: :delete %>
</div>