config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :courses
  resources :plans
  resources :regions
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "students#index"
end

app/models/plan.rb
class Plan < ApplicationRecord
    has_many :courses
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: %i[ show edit update destroy ]

  # GET /plans or /plans.json
  def index
    @plans = Plan.all
  end

  # GET /plans/1 or /plans/1.json
  def show
  end

  # GET /plans/new
  def new
    @plan = Plan.new
  end

  # GET /plans/1/edit
  def edit
  end

  # POST /plans or /plans.json
  def create
    @plan = Plan.new(plan_params)

    respond_to do |format|
      if @plan.save
        format.html { redirect_to plan_url(@plan), notice: "Plan was successfully created." }
        format.json { render :show, status: :created, location: @plan }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plans/1 or /plans/1.json
  def update
    respond_to do |format|
      if @plan.update(plan_params)
        format.html { redirect_to plan_url(@plan), notice: "Plan was successfully updated." }
        format.json { render :show, status: :ok, location: @plan }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1 or /plans/1.json
  def destroy
    @plan.destroy

    respond_to do |format|
      format.html { redirect_to plans_url, notice: "Plan was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def plan_params
      params.require(:plan).permit(:code, :description, :duration)
    end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_form.html.erb
<%= form_with(model: plan) do |form| %>
  <% if plan.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
        <% plan.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :code, style: "display: block" %>
    <%= form.text_field :code %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :duration, style: "display: block" %>
    <%= form.number_field :duration %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/plans/_plan.html.erb
<div id="<%= dom_id plan %>">
  <p>
    <strong>Code:</strong>
    <%= plan.code %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= plan.description %>
  </p>

  <p>
    <strong>Duration:</strong>
    <%= plan.duration %>
  </p>

</div>

app/views/plans/edit.html.erb
<h1>Editing plan</h1>

<%= render "form", plan: @plan %>

<br>

<div>
  <%= link_to "Show this plan", @plan %> |
  <%= link_to "Back to plans", plans_path %>
</div>

app/views/plans/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Plans</h1>

<div id="plans">
  <% @plans.each do |plan| %>
    <%= render plan %>
    <p>
      <%= link_to "Show this plan", plan %>
    </p>
  <% end %>
</div>

<%= link_to "New plan", new_plan_path %>

app/views/plans/new.html.erb
<h1>New plan</h1>

<%= render "form", plan: @plan %>

<br>

<div>
  <%= link_to "Back to plans", plans_path %>
</div>

app/views/plans/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @plan %>

<div>
  <%= link_to "Edit this plan", edit_plan_path(@plan) %> |
  <%= link_to "Back to plans", plans_path %>

  <%= button_to "Destroy this plan", @plan, method: :delete %>
</div>